name: Binary Build
on: [push, pull_request]

jobs:
  binary:
    name: binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver.repos
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
