name: UR Sim
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  ci_binary:
    name: foxy UR Sim
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver.ci.repos
      DOCKER_RUN_OPTS: --network static_test_net
      BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
      IMMEDIATE_TEST_OUTPUT: true
    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          .github/dockerursim/build_and_run_docker_ursim.sh
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
